### ISSUE TITLE
Unrecognized function or variable 'outlierDamping'.

### ISSUE THREAD

**Issue by SwJay** [kal2000/AgnosticMeanAndCovarianceCode#1]
Hi, when I do the test in README, there is an error saying that `outlierDamping` is missing. Is there an existing implementation for that? Thanks for your time.

**Comment by kal2000** [comment]
I added the file back. It was removed one of the later changes to the repo. Hopefully it works now.

**Comment by SwJay** [comment]
Yes, it works perfectly. Thanks for your help.
